---
########## load data dir ##########
cached_data_file: >
  ./data/processed/joint/joint_5M_5M_nogen/dataset_babylm_sampled_5M_cached_{seq_length}.txt,
  ./data/processed/joint/joint_5M_5M_nogen/dataset_tinystories_5M_with_PAR_cached_{seq_length}.txt
cached_valid_data_file: ./data/processed/joint/joint_5M_5M_nogen/DEV_all_segmented_cached_{seq_length}.txt
tokenizer_path: ./outputs/tokenizers/joint/joint_5M_5M_nogen/tokenizer.json
run_name: '10_run_LTG-BERT_baby5m_tiny5m_nogen'
