---
###########
cached_data_file: ./data/processed/babylm/train_100M/all_segmented_cached_{seq_length}.txt
cached_valid_data_file: ./data/processed/babylm/train_100M/DEV_all_segmented_cached_{seq_length}.txt
tokenizer_path: ./outputs/tokenizers/babylm/train_100M/tokenizer.json
run_name: '1_run_LTG-BERT_baby100m_nogen'