d---
###########
cached_data_file: ./data/processed/tinystories/train_100M/TinyStoriesV2-GPT4-train_100M_proc_segmented_with_PAR_cached_128.txt
cached_valid_data_file: ./data/processed/tinystories/train_100M/TinyStoriesV2-GPT4-valid_100M_proc_segmented_with_PAR_cached_128.txt
tokenizer_path: ./outputs/tokenizers/tinystories/train_100M/tokenizer_ltg_bert.json
run_name: '2_run_LTG-BERT_tiny100m_nogen'