---
eval_device: cuda
eval_batch_size: 1
eval_max_length: 512
eval_num_return_sequences: 10
eval_do_sample: true
eval_truncation: true
eval_temperature: 1.0
##################
seed: 42
filetype: json
sample_from: ./data/prompts/tinystories_paper.yaml
is_prompt: True
models: 'roneneldan/TinyStories-33M_HF, gpt_neo_500M, gpt_neo_100M, gpt_neo_75M, gpt_neo_50M, gpt_neo_25M, gpt_neo_10M, gpt_neo_5M'
folder_name: paper_claude_evaluation
