---
eval_device: cuda
eval_batch_size: 8
eval_max_length: 512
eval_num_return_sequences: 10
eval_do_sample: true
eval_truncation: true
eval_temperature: Null
eval_top_k: Null
eval_top_p: 0.95
##################
prob_min: 0.15
prob_max: 0.30
seed: 42
filetype: json
