# Extra-Small configuration
attention_probs_dropout_prob: 0.1
hidden_dropout_prob : 0.1
hidden_size: 32
intermediate_size: 128
max_position_embeddings: 128
position_bucket_size: 32
num_attention_heads: 2
num_hidden_layers: 2
vocab_size: 16384
layer_norm_eps: 1.0e-7