########## load data dir ##########
cached_data_file: ./data/processed/tinystories/train_10M/TinyStoriesV2-GPT4-train_10M_proc_segmented_cached_{seq_length}.txt
cached_valid_data_file: ./data/processed/tinystories/train_10M/TinyStoriesV2-GPT4-valid_10M_proc_segmented_cached_{seq_length}.txt
tokenizer_path: ./outputs/tokenizers/tinystories/train_10M/tokenizer.json
######### training run params ###########
run_name: '2_run_gpt-neo_10m_reg' 
######### eval & log ###########
model_config_file: ./configs/models/gpt-neo/dropout_3.yaml
weight_decay: 0.2
vocab_size: 6411
