########## load data dir ##########
cached_data_file: ./data/processed/tinystories/train_75M/TinyStoriesV2-GPT4-train_75M_proc_segmented_cached_{seq_length}.txt
cached_valid_data_file: ./data/processed/tinystories/train_75M/TinyStoriesV2-GPT4-valid_75M_proc_segmented_cached_{seq_length}.txt
tokenizer_path: ./outputs/tokenizers/tinystories/train_75M/tokenizer.json
######### training run params ###########
run_name: '5_run_gpt-neo_75m_reg' 
######### eval & log ###########
model_config_file: ./configs/models/gpt-neo/dropout_1.yaml
weight_decay: 0.1
vocab_size: 16384 



