---
eval_device: cuda
eval_batch_size: 1
eval_max_length: 512
eval_num_return_sequences: 1
eval_do_sample: false
eval_truncation: true
eval_temperature: Null
eval_top_k: Null
eval_top_p: Null
##################
num_stories: 10
prob_min: 0.15
prob_max: 0.30
seed: 42
folder_name: paper_generations_greedy_NEW
models: 'gpt_neo_50M, gpt_neo_5M, gpt_neo_10M, gpt_neo_25M, gpt_neo_75M, gpt_neo_100M, gpt_neo_500M, roneneldan/TinyStories-33M_HF'
sample_from:  ./data/prompts/paper_figure.yaml 
is_prompt: True